"""Render a ScanReport to Markdown and JSON.

The Markdown form is the human-facing artefact: framework-grouped,
severity-sorted, with the published framework citation visible on
every finding. The JSON form is the machine artefact and is what the
eval harness consumes."""
from __future__ import annotations

import json
from pathlib import Path

from .findings import Finding, Framework, ScanReport, Severity


_SEV_ORDER = {
    Severity.CRITICAL.value: 0,
    Severity.HIGH.value:     1,
    Severity.MEDIUM.value:   2,
    Severity.LOW.value:      3,
    Severity.INFO.value:     4,
}

_FRAMEWORK_TITLES = {
    Framework.OWASP_LLM_2025.value: "OWASP Top 10 for LLM Applications (2025)",
    Framework.NIST_AI_RMF_1.value:  "NIST AI Risk Management Framework 1.0",
    Framework.EU_AI_ACT.value:      "EU AI Act, Regulation (EU) 2024/1689",
}


def _sev_value(f) -> str:
    return f.severity.value if hasattr(f.severity, "value") else f.severity


def _fw_value(f) -> str:
    return f.framework.value if hasattr(f.framework, "value") else f.framework


def _sorted_findings(findings: list[Finding]) -> list[Finding]:
    """Stable severity-then-framework_id sort for predictable output."""
    return sorted(
        findings,
        key=lambda f: (_SEV_ORDER.get(_sev_value(f), 9), f.framework_id),
    )


def render_markdown(report: ScanReport) -> str:
    """Render a single Markdown document from the ScanReport."""
    lines: list[str] = []
    s = report.summary
    lines.append("# AI Governance Audit Report")
    lines.append("")
    lines.append(f"- **Prompt SHA-256:** `{report.prompt_sha256}`")
    lines.append(f"- **Started:** {report.started_at}")
    lines.append(f"- **Finished:** {report.finished_at}")
    lines.append(
        f"- **Total findings:** {s['total_findings']} "
        f"(headline severity: **{s['headline_severity']}**)")
    lines.append(f"- **Judge status:** `{s['judge_status']}`")
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|---|---:|")
    for sev in (Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM,
                 Severity.LOW, Severity.INFO):
        lines.append(f"| {sev.value} | {s['by_severity'].get(sev.value, 0)} |")
    lines.append("")

    if s["by_framework"]:
        lines.append("| Framework | Findings |")
        lines.append("|---|---:|")
        for fw, count in sorted(s["by_framework"].items()):
            lines.append(f"| {fw} | {count} |")
        lines.append("")

    # Findings grouped by framework, severity-sorted within each.
    by_fw: dict[str, list[Finding]] = {}
    for chk in report.checks:
        by_fw.setdefault(_fw_value(chk), []).extend(chk.findings)
    if report.judge and report.judge.findings:
        by_fw.setdefault("judge_llm", []).extend(report.judge.findings)

    if not any(by_fw.values()):
        lines.append("## Findings")
        lines.append("")
        lines.append("_No findings raised by the active rule packs._")
        lines.append("")
    else:
        for fw_key, fw_findings in by_fw.items():
            if not fw_findings:
                continue
            title = _FRAMEWORK_TITLES.get(fw_key, fw_key)
            lines.append(f"## {title}")
            lines.append("")
            for f in _sorted_findings(fw_findings):
                lines.append(
                    f"### `{f.framework_id}` — {f.title} "
                    f"_(severity: {_sev_value(f)})_")
                lines.append("")
                lines.append(f.detail)
                if f.evidence:
                    lines.append("")
                    lines.append("**Evidence:**")
                    for k, v in f.evidence.items():
                        lines.append(f"- `{k}`: `{v}`")
                lines.append("")
                lines.append(f"_Rule id: `{f.rule_id}`._")
                lines.append("")

    if report.judge and not report.judge.findings:
        lines.append("## LLM-as-judge")
        lines.append("")
        status = report.judge.status.value if hasattr(
            report.judge.status, "value") else report.judge.status
        lines.append(f"Status: `{status}`")
        if report.judge.note:
            lines.append("")
            lines.append(report.judge.note)
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_Generated by [`ai-governance-checker`]"
                 "(https://github.com/thunderstornX/ai-governance-checker). "
                 "This report is an audit aid; it is not a compliance "
                 "certificate._")
    return "\n".join(lines).rstrip() + "\n"


def render_json(report: ScanReport) -> str:
    """Render a deterministic, sort_keys-true JSON document."""
    return json.dumps(report.to_dict(), indent=2, sort_keys=True)


def write_report(
    report: ScanReport,
    *,
    output_path: Path,
) -> tuple[Path, Path]:
    """Write Markdown and JSON to disk.

    Returns ``(md_path, json_path)``. If ``output_path`` ends in
    ``.md`` we mirror the JSON next to it as ``.json`` (and vice
    versa); if it ends in neither we treat it as a stem and write
    both extensions."""
    output_path = Path(output_path).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if output_path.suffix.lower() == ".md":
        md_path = output_path
        json_path = output_path.with_suffix(".json")
    elif output_path.suffix.lower() == ".json":
        json_path = output_path
        md_path = output_path.with_suffix(".md")
    else:
        md_path = output_path.with_suffix(".md")
        json_path = output_path.with_suffix(".json")

    md_path.write_text(render_markdown(report), encoding="utf-8")
    json_path.write_text(render_json(report), encoding="utf-8")
    return md_path, json_path
